build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
  i386: "ghcr.io/home-assistant/i386-base-debian:bullseye"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Pawns add-on"
  org.opencontainers.image.description: "Make passive money online by completing surveys and sharing your internet."
  org.opencontainers.image.source: "https://github.com/sesousa/homeassistant-addons/pawns"
  org.opencontainers.image.licenses: "MIT License"
args:
  TEMPIO_VERSION: "2021.09.0"
