name: "Pawns"
description: "Make passive money online by completing surveys and sharing your internet."
version: "1.0.0"
slug: "pawns"
url: "https://pawns.app/?r=2267482"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  email: null
  password: null
  device: null
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  email: "str"
  password: "password"
  device: "str"
